# Generated by Django 3.2.3 on 2021-07-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
