# Generated by Django 3.2.3 on 2021-07-16 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notifications',
            unique_together={('ricipient', 'group')},
        ),
    ]
