# Generated by Django 3.2.3 on 2021-07-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='is_read',
        ),
    ]
